version: "3.9"
services:

  api:
    image: piatoss3612/issuer-node:latest
    ports:
      - "3001:3001"
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && ./migrate && ./platform"

  pending_publisher:
    image: piatoss3612/issuer-node:latest
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s &&  ./pending_publisher"

  initializer:
    image: piatoss3612/issuer-node:latest
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && ./migrate && ./issuer_initializer"

networks:
  default:
    name: issuer-network
